// import { FileText, Clock, CheckCircle } from 'lucide-react'

// export default function ReportCard({ report }) {
//   if (!report) return null

//   const typeLabels = {
//     upcoming_deadlines: 'Upcoming Deadlines',
//     top_issues:         'Top Issues',
//     satisfaction_index: 'Satisfaction Index',
//   }

//   const generated = new Date(report.generated).toLocaleString('en-IN', {
//     dateStyle: 'medium',
//     timeStyle: 'short',
//   })

//   return (
//     <div style={{
//       background: 'var(--bg-card)',
//       border: '1px solid var(--border)',
//       borderRadius: 'var(--radius)',
//       padding: 24,
//       animation: 'fadeUp 0.25s ease',
//     }}>
//       {/* Header */}
//       <div style={{
//         display: 'flex',
//         alignItems: 'center',
//         justifyContent: 'space-between',
//         marginBottom: 20,
//         paddingBottom: 16,
//         borderBottom: '1px solid var(--border)',
//       }}>
//         <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
//           <div style={{
//             width: 36,
//             height: 36,
//             borderRadius: 'var(--radius-sm)',
//             background: 'var(--accent-glow)',
//             border: '1px solid var(--accent)',
//             display: 'flex', alignItems: 'center', justifyContent: 'center',
//           }}>
//             <FileText size={16} color="var(--accent)" />
//           </div>
//           <div>
//             <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-1)' }}>
//               {typeLabels[report.type] || report.type}
//             </div>
//             <div style={{ fontSize: 12, color: 'var(--text-3)', display: 'flex', alignItems: 'center', gap: 4, marginTop: 2 }}>
//               <Clock size={11} /> {generated}
//             </div>
//           </div>
//         </div>
//         <div style={{
//           display: 'flex', alignItems: 'center', gap: 5,
//           fontSize: 12, color: 'var(--success)',
//           background: 'rgba(62,207,142,0.08)',
//           padding: '4px 10px', borderRadius: 99,
//           border: '1px solid rgba(62,207,142,0.2)',
//         }}>
//           <CheckCircle size={12} /> Generated
//         </div>
//       </div>

//       {/* Scores (satisfaction index only) */}
//       {report.scores && Object.keys(report.scores).length > 0 && (
//         <div style={{
//           display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap',
//         }}>
//           {Object.entries(report.scores).map(([group, score]) => (
//             <div key={group} style={{
//               flex: 1, minWidth: 100,
//               background: 'var(--bg-hover)',
//               border: '1px solid var(--border-lite)',
//               borderRadius: 'var(--radius-sm)',
//               padding: '12px 16px',
//               textAlign: 'center',
//             }}>
//               <div style={{
//                 fontSize: 22,
//                 fontFamily: 'var(--font-display)',
//                 color: score >= 7 ? 'var(--success)' : score >= 5 ? 'var(--accent2)' : 'var(--danger)',
//               }}>
//                 {score}
//               </div>
//               <div style={{ fontSize: 11, color: 'var(--text-3)', marginTop: 2, textTransform: 'capitalize' }}>
//                 {group}
//               </div>
//             </div>
//           ))}
//         </div>
//       )}

//       {/* Report body */}
//       <pre style={{
//         whiteSpace: 'pre-wrap',
//         wordBreak: 'break-word',
//         fontSize: 13.5,
//         lineHeight: 1.75,
//         color: 'var(--text-2)',
//         fontFamily: 'var(--font-body)',
//       }}>
//         {report.report}
//       </pre>
//     </div>
//   )
// }

// components/ReportCard.jsx
import { FileText, Clock, CheckCircle, Download } from 'lucide-react'

function exportTxt(report) {
  const typeLabels = {
    upcoming_deadlines: 'Upcoming Deadlines Report',
    top_issues:         'Top Issues Report',
    satisfaction_index: 'Satisfaction Index Report',
  }

  const generated = new Date(report.generated).toLocaleString('en-IN', {
    dateStyle: 'long', timeStyle: 'short',
  })

  let content = `VIIT UNIVERSITY SUPPORT AGENT\n`
  content += `${'='.repeat(50)}\n`
  content += `${typeLabels[report.type] || report.type}\n`
  content += `Generated: ${generated}\n`
  content += `${'='.repeat(50)}\n\n`

  if (report.scores && Object.keys(report.scores).length > 0) {
    content += `SCORES\n${'-'.repeat(30)}\n`
    for (const [group, score] of Object.entries(report.scores)) {
      content += `${group.charAt(0).toUpperCase() + group.slice(1)}: ${score}/10\n`
    }
    content += `\n`
  }

  content += report.report
  content += `\n\n${'='.repeat(50)}\n`
  content += `Generated by VIIT Support Agent\n`

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `VIIT_${report.type}_${Date.now()}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

export default function ReportCard({ report }) {
  if (!report) return null

  const typeLabels = {
    upcoming_deadlines: 'Upcoming Deadlines',
    top_issues:         'Top Issues',
    satisfaction_index: 'Satisfaction Index',
  }

  const generated = new Date(report.generated).toLocaleString('en-IN', {
    dateStyle: 'medium', timeStyle: 'short',
  })

  return (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: 24, animation: 'fadeUp 0.25s ease' }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20, paddingBottom: 16, borderBottom: '1px solid var(--border)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ width: 36, height: 36, borderRadius: 'var(--radius-sm)', background: 'var(--accent-glow)', border: '1px solid var(--accent)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <FileText size={16} color="var(--accent)" />
          </div>
          <div>
            <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-1)' }}>{typeLabels[report.type] || report.type}</div>
            <div style={{ fontSize: 12, color: 'var(--text-3)', display: 'flex', alignItems: 'center', gap: 4, marginTop: 2 }}>
              <Clock size={11} /> {generated}
            </div>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 12, color: 'var(--success)', background: 'rgba(62,207,142,0.08)', padding: '4px 10px', borderRadius: 99, border: '1px solid rgba(62,207,142,0.2)' }}>
            <CheckCircle size={12} /> Generated
          </div>
          {/* Export button */}
          <button
            onClick={() => exportTxt(report)}
            style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: 'var(--text-2)', background: 'var(--bg-hover)', padding: '5px 12px', borderRadius: 99, border: '1px solid var(--border-lite)', cursor: 'pointer', transition: 'all var(--transition)' }}
            onMouseEnter={e => { e.currentTarget.style.color = 'var(--text-1)'; e.currentTarget.style.borderColor = 'var(--accent)' }}
            onMouseLeave={e => { e.currentTarget.style.color = 'var(--text-2)'; e.currentTarget.style.borderColor = 'var(--border-lite)' }}
          >
            <Download size={12} /> Export .txt
          </button>
        </div>
      </div>

      {/* Scores (satisfaction index only) */}
      {report.scores && Object.keys(report.scores).length > 0 && (
        <div style={{ display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap' }}>
          {Object.entries(report.scores).map(([group, score]) => (
            <div key={group} style={{ flex: 1, minWidth: 100, background: 'var(--bg-hover)', border: '1px solid var(--border-lite)', borderRadius: 'var(--radius-sm)', padding: '12px 16px', textAlign: 'center' }}>
              <div style={{ fontSize: 22, fontFamily: 'var(--font-display)', color: score >= 7 ? 'var(--success)' : score >= 5 ? 'var(--accent2)' : 'var(--danger)' }}>
                {score}
              </div>
              <div style={{ fontSize: 11, color: 'var(--text-3)', marginTop: 2, textTransform: 'capitalize' }}>{group}</div>
            </div>
          ))}
        </div>
      )}

      {/* Report body */}
      <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word', fontSize: 13.5, lineHeight: 1.75, color: 'var(--text-2)', fontFamily: 'var(--font-body)' }}>
        {report.report}
      </pre>
    </div>
  )
}